import 'package:hive/hive.dart';

part 'task.g.dart'; // This part file will be generated by Hive

@HiveType(typeId: 0) // Register the type with an ID (ensure this ID is unique in your app)
class Task extends HiveObject {
  @HiveField(0)
  int id;

  @HiveField(1)
  String title;

  @HiveField(2)
  String? description;

  @HiveField(3)
  DateTime dueDate;

  @HiveField(4)
  int priority;

  @HiveField(5)
  bool isCompleted;

  Task({
    required this.id,
    required this.title,
    this.description,
    required this.dueDate,
    this.priority = 1, // Default priority level
    this.isCompleted = false, // Default is false, meaning task is not completed
  });

  // Convert a Task object into a Map object (for legacy code or custom usage)
  // This may not be necessary for Hive, but it's good for custom usage
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'dueDate': dueDate.toIso8601String(),
      'priority': priority,
      'isCompleted': isCompleted ? 1 : 0, // Store as 1 or 0
    };
  }

  // Convert a Map object back into a Task object (for legacy code or custom usage)
  // This may not be necessary for Hive, but it's good for custom usage
  factory Task.fromMap(Map<String, dynamic> map) {
    return Task(
      id: map['id'],
      title: map['title'],
      description: map['description'],
      dueDate: DateTime.parse(map['dueDate']),
      priority: map['priority'],
      isCompleted: map['isCompleted'] == 1, // Convert 1 or 0 to bool
    );
  }
}
